from Grafo import Graph

def fill_graph(g):
    g.add_edge("elvas", "borba", 15)
    g.add_edge("borba", "estremoz", 15)
    g.add_edge("estremoz", "evora", 40)
    g.add_edge("evora", "montemor", 20)
    g.add_edge("montemor", "vendasnovas", 15)
    g.add_edge("vendasnovas", "lisboa", 50)
    g.add_edge("elvas", "arraiolos", 50)
    g.add_edge("arraiolos", "alcacer", 90)
    g.add_edge("alcacer", "palmela", 35)
    g.add_edge("palmela", "almada", 25)
    g.add_edge("palmela", "barreiro", 25)
    g.add_edge("barreiro", "palmela", 30)
    g.add_edge("almada", "lisboa", 15)
    g.add_edge("elvas", "alandroal", 40)
    g.add_edge("alandroal", "redondo", 25)
    g.add_edge("redondo", "monsaraz", 30)
    g.add_edge("monsaraz", "barreiro", 120)
    g.add_edge("barreiro", "baixadabanheira", 5)
    g.add_edge("baixadabanheira", "moita", 7)

    g.add_edge("alcochete", "lisboa", 20)


#colocar heuristicas em condiçoes
def heuristicaCombustivel(g):
    g.add_heuristica("elvas", 270)
    g.add_heuristica("borba", 250)
    g.add_heuristica("estremoz", 145)
    g.add_heuristica("evora", 95)
    g.add_heuristica("montemor", 70)
    g.add_heuristica("vendasnovas", 45)
    g.add_heuristica("arraiolos", 220)
    g.add_heuristica("alcacer", 140)
    g.add_heuristica("palmela", 85)
    g.add_heuristica("almada", 25)
    g.add_heuristica("alandroal", 180)
    g.add_heuristica("redondo", 170)
    g.add_heuristica("monsaraz", 120)
    g.add_heuristica("barreiro", 30)
    g.add_heuristica("baixadabanheira", 33)
    g.add_heuristica("moita", 35)
    g.add_heuristica("alcochete", 26)
    g.add_heuristica("lisboa", 0)

#colocar heuristicas em condiçoes
def heuristicaTemporais(g):
    g.add_heuristica("elvas", 270)
    g.add_heuristica("borba", 250)
    g.add_heuristica("estremoz", 145)
    g.add_heuristica("evora", 95)
    g.add_heuristica("montemor", 70)
    g.add_heuristica("vendasnovas", 45)
    g.add_heuristica("arraiolos", 220)
    g.add_heuristica("alcacer", 140)
    g.add_heuristica("palmela", 85)
    g.add_heuristica("almada", 25)
    g.add_heuristica("alandroal", 180)
    g.add_heuristica("redondo", 170)
    g.add_heuristica("monsaraz", 120)
    g.add_heuristica("barreiro", 30)
    g.add_heuristica("baixadabanheira", 33)
    g.add_heuristica("moita", 35)
    g.add_heuristica("alcochete", 26)
    g.add_heuristica("lisboa", 0)

#colocar heuristicas em condiçoes
def heuristicaTransito(g):
    g.add_heuristica("elvas", 270)
    g.add_heuristica("borba", 250)
    g.add_heuristica("estremoz", 145)
    g.add_heuristica("evora", 95)
    g.add_heuristica("montemor", 70)
    g.add_heuristica("vendasnovas", 45)
    g.add_heuristica("arraiolos", 220)
    g.add_heuristica("alcacer", 140)
    g.add_heuristica("palmela", 85)
    g.add_heuristica("almada", 25)
    g.add_heuristica("alandroal", 180)
    g.add_heuristica("redondo", 170)
    g.add_heuristica("monsaraz", 120)
    g.add_heuristica("barreiro", 30)
    g.add_heuristica("baixadabanheira", 33)
    g.add_heuristica("moita", 35)
    g.add_heuristica("alcochete", 26)
    g.add_heuristica("lisboa", 0)